//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ateler
{
    using System;
    using System.Collections.Generic;
    //using System.Threading;

    public partial class Session
    {
        
        public int CodeSession { get; set; }
        public Nullable<System.DateTime> DateSession { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> CodePerson { get; set; }
    
        public virtual Person Person { get; set; }

    }
}
