//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ateler
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int CodeUser { get; set; }
        public string LoginUser { get; set; }
        public string Paassword { get; set; }
        public Nullable<int> CodeRole { get; set; }
        public Nullable<int> CodePerson { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Role Role { get; set; }
    }
}
